version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    user: 1000:1000
    volumes:
      - .:/var/www/html

  database:
    image: mysql:5.7
    ports:
      - 3307:3306
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql_databases
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "middleware"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"